backend:
  name: github
  repo: babosuho/my-blog
  branch: master
  base_url: https://my-blog.broad-limit-9d35.workers.dev
  auth_endpoint: /api/auth

media_folder: "src/assets"
public_folder: "../../assets"

collections:
  - name: "blog"
    label: "블로그"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "설명 (SEO용)", name: "description", widget: "string" }
      - { label: "발행일", name: "pubDate", widget: "datetime" }
      - { label: "대표 이미지", name: "heroImage", widget: "image", required: false }
      - { label: "본문", name: "body", widget: "markdown" }
